name: feature_request
description: Suggest an idea for this project
title: "[Suggest]: "
labels: Suggest
assignees: pangolp, sayghteight, DZywolf
body:
  - type: textarea
    id: feature
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
